apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "8"
    limits.memory: 10Gi
    configmaps: 100
    persistentvolumeclaims: 100
    pods: 100
    resourcequotas: 100
    services: 100
    services.loadbalancers: 100
    services.nodeports: 100
    secrets: 100
